services:
  amqp:
    image: rabbitmq:latest
    hostname: calhacks-rabbit
    restart: always
    ports:
      - ${RABBIT_PORT}:${RABBIT_PORT}

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_AUTH_METHOD=md5
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - calhacks-pg:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - calhacks-redis-data:/data


volumes:
  calhacks-pg:
    driver: local
  calhacks-redis-data:
    driver: local
