"""adding_optional_subtask_count_to_task_table

Revision ID: c9db92499346
Revises: 9a40baa82186
Create Date: 2024-10-19 09:22:00.839506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9db92499346'
down_revision: Union[str, None] = '9a40baa82186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('subtask_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'subtask_count')
    # ### end Alembic commands ###
