"""creating_subtask_table

Revision ID: f40bcf984fe2
Revises: c9db92499346
Create Date: 2024-10-20 01:28:02.557640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40bcf984fe2'
down_revision: Union[str, None] = 'c9db92499346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtask',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_assigned', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtask_id'), 'subtask', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtask_id'), table_name='subtask')
    op.drop_table('subtask')
    # ### end Alembic commands ###
